services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=tweeter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
    ports:
      - 5432:5432

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 1323:1323
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
